# Generated by Django 3.1.3 on 2020-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlyAtWill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iatacode', models.CharField(blank=True, db_column='IATACode', max_length=3, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=30, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
            ],
            options={
                'db_table': 'Airport',
                'managed': False,
            },
        ),
    ]
