# Generated by Django 3.1.3 on 2020-11-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoairline',
            name='ArrTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='djangoairline',
            name='DeptTime',
            field=models.TimeField(),
        ),
    ]
